default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  gssencmode: disable

development:
  <<: *default
  database: prehrajto_scraper

test:
  <<: *default
  database: prehrajto_scraper_test

production:
  <<: *default
  database: prehrajto_scraper
  username: postgres
  password: password
